config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  CATEGORY = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :name, :address, presence: true
  validates :category, inclusion: { in: CATEGORY}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      redirect_to new_restaurant_path
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant

    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container col-6 ">
  <h1 class="text-center">Restaurants List</h1>
  <p>
  <% @restaurants.each do |restaurant| %>
  <li class="p-2 bg-light border"><%= restaurant.name %> <%= link_to "details", restaurant_path(restaurant)  %></li>
  <% end %>
  </p>

  <%= link_to new_restaurant_path do%>
      <i class="fas fa-plus">  Create a new restaurant</i>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="container col-6">
<h1 class="text-center">Create Your New Restaurant</h1>
<h2 ><%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category %>
  <%= f.submit %>
<% end %>
</h2>

<p><%= link_to restaurants_path do%>
  <i class="fas fa-arrow-alt-circle-left"> Back to Lists</i>
<% end %>
</p>
</div>

app/views/restaurants/show.html.erb
<div class="container col-6">
  <h1 class="p-2 bg-light border text-center"> Restaurant <%= @restaurant.name%></h1>
  <p class="p-2 bg-light border"> Location :<%= @restaurant.address %></p>
  <p class="p-2 bg-light border"> Phone Number :<%= @restaurant.phone_number %> </p>
  <p class="p-2 bg-light border">Category :<%= @restaurant.category %> </p>
  <p> <% @restaurant.reviews.each do |review| %>
    <p>Restaurant's Review: <br> <%= review.content  %>
    <%= review.rating %> </p>
    <% end %> </p>
  <%= link_to restaurants_path do%>
      <i class="fas fa-arrow-alt-circle-left"> Back to Lists</i>
  <% end %>

  <br>

  <%= link_to new_restaurant_review_path(@restaurant) do%>
    <i class="fas fa-calendar-edit">Write a review</i>
  <% end %>

</div>

app/views/reviews/new.html.erb
<div class="container col-6">
<h1>Write a review for <%= @restaurant.name %></h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit %>
<% end %>

<p class="p-3">
  <%= link_to restaurant_path(@restaurant) do%>
      <i class="fas fa-arrow-alt-circle-left"> Back to Lists</i>
  <% end %>
</p>
</div>